# Generated by Django 5.0.4 on 2024-05-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=180)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("linkedin_link", models.URLField()),
                ("highest_education_lvl", models.CharField(max_length=200)),
                ("major_field", models.CharField(max_length=200)),
                ("graduation_year", models.CharField(max_length=10)),
                ("have_work_experience", models.BooleanField(default=False)),
                ("company_name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=150)),
                ("date_joinned", models.DateField()),
                ("date_quit", models.DateField()),
                ("achivements", models.CharField(max_length=300)),
                ("programming_languages", models.CharField(max_length=350)),
                ("frameworks", models.CharField(max_length=300)),
                ("non_tech_skills", models.CharField(max_length=350)),
                ("professional_qualifications", models.CharField(max_length=350)),
                ("target_role", models.CharField(max_length=100)),
                ("carrer_goals", models.CharField(max_length=400)),
            ],
        ),
    ]
