# Generated by Django 5.0.4 on 2024-05-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="linkedin_link",
            field=models.URLField(blank=True),
        ),
    ]
