# Generated by Django 5.0.6 on 2024-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0002_alter_userdata_linkedin_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="course_name",
            field=models.CharField(blank=True, default="BCA", max_length=100),
        ),
    ]
