# Generated by Django 5.0.6 on 2024-05-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0003_userdata_course_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="highest_education_lvl",
            new_name="university_name",
        ),
    ]
