# Generated by Django 5.0.6 on 2024-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0004_rename_highest_education_lvl_userdata_university_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="gpa_out_of_5",
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=4),
        ),
    ]
