# Generated by Django 5.0.6 on 2024-05-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_data", "0005_userdata_gpa_out_of_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata", name="courses", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="educational_achivements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userdata", name="projects", field=models.TextField(blank=True),
        ),
    ]
