# Generated by Django 5.0.6 on 2024-05-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_data",
            "0006_userdata_courses_userdata_educational_achivements_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="userdata", name="achivements",),
        migrations.RemoveField(model_name="userdata", name="date_joinned",),
        migrations.RemoveField(model_name="userdata", name="date_quit",),
        migrations.AddField(
            model_name="userdata",
            name="achievements",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="userdata",
            name="location",
            field=models.CharField(default="moon", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdata",
            name="months_worked",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userdata",
            name="reason_for_leaving",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="responsibilities",
            field=models.TextField(default="default"),
        ),
        migrations.AddField(
            model_name="userdata",
            name="skills_utilized",
            field=models.CharField(default="python", max_length=300),
        ),
        migrations.AddField(
            model_name="userdata",
            name="supervisor_contact",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="supervisor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
